# TopicGPT Tuning: c-TF-IDF & Topic Filtering Optimization

This notebook tunes the c-TF-IDF and topic filtering parameters for TopicGPT's
assignment stage. It **reuses** existing assignment checkpoints from the modeling
phase and grid-searches over:

- **`max_df`** — c-TF-IDF maximum document frequency threshold
- **`min_docs`** — Minimum documents per topic to keep

Each subject uses its best sentence transformer model identified during modeling.

In [1]:
import os
import gc
import pickle
import pandas as pd
import numpy as np
from pathlib import Path
from itertools import product
from tqdm import tqdm
from gensim.corpora import Dictionary
from gensim.models import CoherenceModel
from sklearn.feature_extraction.text import TfidfVectorizer
from itertools import combinations
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity as cos_sim
import warnings

warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore", category=DeprecationWarning)
os.environ["TOKENIZERS_PARALLELISM"] = "false"

## Configuration

In [2]:
LIST_SUBJECT = ["cs", "math", "physics"]
VERSION = "v1"

BASE_DIR = Path("../../../../data/preprocess")
CHECKPOINT_DIR = Path("../../../../models/topicGpt")
RESULT_DIR = Path("../../../../results/topicGpt/tunning")
TUNING_CKPT_DIR = CHECKPOINT_DIR  # tuning checkpoints go alongside modeling ones
EMBEDDING_DIR = Path("../../../../embedding")

# Best embedding model per subject (from modeling phase)
BEST_MODEL_MAP = {
    "cs":      "sentence_transformers_all_MiniLM_L6_v2",
    "math":    "sentence_transformers_all_MiniLM_L6_v2",
    "physics":  "all_distilroberta_v1",
}

# --- Tuning grid ---
MAX_DF_VALUES   = [0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
MIN_DOCS_VALUES = [10, 25, 50, 100, 150, 200, 250]

TOP_N_WORDS = 10
RBO_P = 0.9

# Create output dirs
for subject in LIST_SUBJECT:
    (RESULT_DIR / subject).mkdir(parents=True, exist_ok=True)

print(f"Subjects: {LIST_SUBJECT}")
print(f"max_df grid:   {MAX_DF_VALUES}")
print(f"min_docs grid: {MIN_DOCS_VALUES}")
print(f"Total combos per subject: {len(MAX_DF_VALUES) * len(MIN_DOCS_VALUES)}")
print(f"Results dir: {RESULT_DIR.resolve()}")

Subjects: ['cs', 'math', 'physics']
max_df grid:   [0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
min_docs grid: [10, 25, 50, 100, 150, 200, 250]
Total combos per subject: 42
Results dir: /home/nedo/Kuliah/TA/Program/results/topicGpt/tunning

## Checkpoint Utilities

In [3]:
def save_checkpoint(data, name: str, subject: str):
    """Save checkpoint to disk."""
    path = TUNING_CKPT_DIR / subject / f"{name}.pkl"
    with open(path, "wb") as f:
        pickle.dump(data, f)
    print(f"  Checkpoint saved: {path}")

def load_checkpoint(name: str, subject: str):
    """Load checkpoint from disk, return None if not found."""
    path = TUNING_CKPT_DIR / subject / f"{name}.pkl"
    if path.exists():
        with open(path, "rb") as f:
            data = pickle.load(f)
        print(f"  Checkpoint loaded: {path}")
        return data
    return None

## Data Loading

In [4]:
def load_dataset(subject: str) -> pd.DataFrame:
    """Load preprocessed dataset."""
    file_path = BASE_DIR / subject / "emb" / f"{VERSION}.csv"
    df = pd.read_csv(file_path)
    return df

all_data = {}
for subject in LIST_SUBJECT:
    df = load_dataset(subject)
    all_data[subject] = df
    print(f"{subject}: {len(df):,} documents loaded")

print(f"\nAll subjects loaded.")

cs: 165,756 documents loaded
math: 157,085 documents loaded
physics: 146,311 documents loaded

All subjects loaded.

## Generate Base Assignments

Instead of loading filtered assignment checkpoints from the modeling phase, we dynamically recompute the base assignments using the best sentence transformer for each subject.
This ensures zero filtering (`min_docs=0`) before the tuning loop begins.

In [5]:
MODEL_HF_MAP = {
    "all_distilroberta_v1": "all-distilroberta-v1",
    "sentence_transformers_all_MiniLM_L6_v2": "sentence-transformers/all-MiniLM-L6-v2"
}

# def load_doc_embeddings(subject: str, model_name: str):
#     path = EMBEDDING_DIR / subject / "emb" / f"{model_name}.npy"
#     if path.exists():
#         return np.load(path)
#     return None
def load_doc_embeddings(subject: str, model_name: str) -> np.ndarray:
    meta_path = EMBEDDING_DIR / subject / f"{model_name}_meta_v1.npy"
    if not meta_path.exists():
        meta_path = EMBEDDING_DIR / subject / f"{model_name}_v1_meta.npy"
    meta  = np.load(meta_path, allow_pickle=True).item()
    n, d  = meta["n_samples"], meta["emb_dim"]
    return np.memmap(
        EMBEDDING_DIR / subject / f"{model_name}_v1.mmap",
        dtype="float32", mode="r", shape=(n, d)
    )

def assign_topics_st(doc_embs, enriched_topics: dict, model_name: str, batch_size=2000, threshold=0.5):
    """Cosine-similarity assignment using a SentenceTransformer model with outlier thresholding."""
    hf_name  = MODEL_HF_MAP.get(model_name, model_name)
    st_model = SentenceTransformer(hf_name)
    
    topic_ids  = sorted(enriched_topics.keys())
    descs      = [enriched_topics[t].get("enriched_description") or enriched_topics[t]["description"]
                  for t in topic_ids]
    
    topic_embs = st_model.encode(descs, normalize_embeddings=True, batch_size=32, show_progress_bar=False)
    
    rows = []
    for start in tqdm(range(0, len(doc_embs), batch_size), desc=f"Assigning ({model_name})", leave=False):
        batch = np.array(doc_embs[start:start+batch_size])
        
        sims  = cos_sim(batch, topic_embs)
        best  = sims.argmax(axis=1)
        scores = sims.max(axis=1)
        
        for idx, (bi, sc) in enumerate(zip(best, scores)):
            if sc >= threshold:
                tid = topic_ids[bi]
                label = enriched_topics[tid]["label"]
            else:
                tid = -1
                label = "Outlier / Unassigned"
                
            rows.append({
                "doc_idx": start + idx, 
                "topic_id": tid,
                "topic_label": label,
                "confidence": float(sc)
            })
    return pd.DataFrame(rows)

all_base_assignments = {}

for subject in LIST_SUBJECT:
    best_model = BEST_MODEL_MAP[subject]
    
    # 1. Load document embeddings
    doc_embs = load_doc_embeddings(subject, best_model)
    if doc_embs is None:
        print(f"  ERROR: No doc embeddings found for {subject}/{best_model}")
        continue
        
    # 2. Load enriched topics
    enriched_ckpt = load_checkpoint("enrichment", subject)
    if not enriched_ckpt:
        print(f"  ERROR: No enriched topics found for {subject}")
        continue
        
    enriched_topics = enriched_ckpt["enriched_topics"]
    
    # 3. Assign topics
    print(f"Reassigning {subject} using {best_model}...")
    df_assign = assign_topics_st(doc_embs, enriched_topics, best_model)
    
    all_base_assignments[subject] = df_assign
    n_docs = len(df_assign)
    n_topics = df_assign["topic_id"].nunique()
    print(f"  {subject}: {n_docs:,} assignments, {n_topics} unique topics")

print(f"\nGenerated base assignments for {len(all_base_assignments)}/{len(LIST_SUBJECT)} subjects.")

  Checkpoint loaded: ../../../../models/topicGpt/cs/enrichment.pkl
Reassigning cs using sentence_transformers_all_MiniLM_L6_v2...

  cs: 165,756 assignments, 617 unique topics
  Checkpoint loaded: ../../../../models/topicGpt/math/enrichment.pkl
Reassigning math using sentence_transformers_all_MiniLM_L6_v2...

  math: 157,085 assignments, 611 unique topics
  Checkpoint loaded: ../../../../models/topicGpt/physics/enrichment.pkl
Reassigning physics using all_distilroberta_v1...

  physics: 146,311 assignments, 498 unique topics

Generated base assignments for 3/3 subjects.

## Tuning Functions

In [6]:
def filter_and_reindex_topics(df_assign: pd.DataFrame, min_docs: int) -> pd.DataFrame:
    """Filter topics with fewer than min_docs documents and reindex."""
    df_filtered = df_assign[df_assign["topic_id"] != -1].copy()

    topic_counts = df_filtered["topic_id"].value_counts()
    valid_topics = topic_counts[topic_counts >= min_docs].index

    df_filtered = df_filtered[df_filtered["topic_id"].isin(valid_topics)].copy()

    unique_topics = sorted(df_filtered["topic_id"].unique())
    topic_mapping = {old_id: new_idx for new_idx, old_id in enumerate(unique_topics)}

    df_filtered["original_topic_id"] = df_filtered["topic_id"]
    df_filtered["topic_id"] = df_filtered["topic_id"].map(topic_mapping)

    return df_filtered


def compute_topic_words_ctfidf(assignment_df: pd.DataFrame, texts: list,
                                max_df: float = 0.8, top_n: int = 10) -> dict:
    """Extract topic words using c-TF-IDF with parametric max_df."""
    topic_docs = []
    tids = []

    for tid, grp in assignment_df.groupby("topic_id"):
        if tid == -1:
            continue
        combined_text = " ".join([texts[i] for i in grp["doc_idx"].tolist() if i < len(texts)])
        topic_docs.append(combined_text)
        tids.append(tid)

    if not topic_docs:
        return {}

    vec = TfidfVectorizer(
        stop_words="english",
        max_features=10000,
        ngram_range=(1, 2),
        max_df=max_df
    )

    tfidf_matrix = vec.fit_transform(topic_docs)
    feature_names = vec.get_feature_names_out()

    topic_words = {}
    for i, tid in enumerate(tids):
        row = tfidf_matrix.getrow(i).toarray().flatten()
        top_ids = row.argsort()[-top_n:][::-1]
        topic_words[tid] = [feature_names[idx] for idx in top_ids if row[idx] > 0]
    return topic_words

def rbo(list1, list2, p=0.9):
    if not list1 and not list2:
        return 1.0
    if not list1 or not list2:
        return 0.0

    # assign short (S) and long (L)
    if len(list1) <= len(list2):
        S, L = list1, list2
    else:
        S, L = list2, list1

    s, l = len(S), len(L)

    S_seen = set()
    L_seen = set()

    X = 0  # overlap
    rbo = 0.0
    disjoint = 0.0
    ext_term = 0.0

    for d in range(l):
        if d < s:
            s_item = S[d]
            S_seen.add(s_item)
        else:
            s_item = None

        l_item = L[d]
        L_seen.add(l_item)

        overlap_incr = 0

        if d < s:
            if s_item == l_item:
                overlap_incr = 1
            else:
                if s_item in L_seen:
                    overlap_incr += 1
                if l_item in S_seen:
                    overlap_incr += 1
        else:
            if l_item in S_seen:
                overlap_incr = 1

        X += overlap_incr

        if d < s:
            A_d = 2.0 * X / (len(S_seen) + len(L_seen))
        else:
            A_d = X / (d + 1)

        rbo += (1 - p) * (p ** d) * A_d

        if d < s:
            ext_term = A_d * (p ** (d + 1))
        else:
            X_s = X - overlap_incr if d == s else X_s
            disjoint += (1 - p) * (p ** d) * (
                X_s * (d + 1 - s) / ((d + 1) * s)
            )
            ext_term = (
                ((X - X_s) / (d + 1) + X_s / s)
                * (p ** (d + 1))
            )

        # optional optimization (safe)
        if p ** d < 1e-12:
            break

    return min(max(rbo + disjoint + ext_term, 0.0), 1.0)

def compute_coherence_irbo(assignment_df: pd.DataFrame, texts: list,
                           max_df: float = 0.8, top_n: int = 10) -> dict:
    """Compute C_v coherence and IRBO diversity with parametric max_df."""
    topic_words = compute_topic_words_ctfidf(assignment_df, texts, max_df, top_n)
    word_lists  = [v for v in topic_words.values() if v]

    tokenized = [t.lower().split() for t in texts]

    # Flatten bigrams to unigrams for gensim
    gensim_word_lists = []
    for words in word_lists:
        topic_unigrams = []
        for w in words:
            topic_unigrams.extend(w.split())
        unique_unigrams = list(dict.fromkeys(topic_unigrams))[:top_n]
        gensim_word_lists.append(unique_unigrams)

    try:
        dct = Dictionary(tokenized)
        cm  = CoherenceModel(
            topics=gensim_word_lists,
            texts=tokenized,
            dictionary=dct,
            coherence="c_v",
            processes=5
        )
        cv = cm.get_coherence()
    except Exception as e:
        print(f"    Coherence error: {e}")
        cv = 0.0
    def irbo(lists1, lists2, p = 0.9):
        return 1 - rbo(lists1, lists2)



    pairs = list(combinations(word_lists, 2))
    irbo  = float(np.mean([irbo(a, b) for a, b in pairs])) if pairs else 0.0
    tq    = 2 * cv * irbo / (cv + irbo + 1e-8)

    return {"coherence": cv, "irbo": irbo, "topic_quality": tq}

## Topic Counts Recap

Display all topics with their document counts for all subjects before the tuning loop.

In [7]:
for subject, df_assign in all_base_assignments.items():
    print(f"=== {subject.upper()} ===")
    topic_counts = df_assign["topic_id"].value_counts().sort_values(ascending=False)
    display(pd.DataFrame({'topic': topic_counts.index, 'doc_count': topic_counts.values}))
    print("\n")

=== CS ===

     topic  doc_count
0       -1      68006
1      432       1967
2      573       1724
3      546       1704
4      578       1533
..     ...        ...
612    345          2
613     63          2
614    453          1
615    104          1
616    608          1

[617 rows x 2 columns]

=== MATH ===

     topic  doc_count
0       -1      76778
1      519       1339
2      101        945
3       43        848
4      439        777
..     ...        ...
606    309          2
607    449          1
608    113          1
609    105          1
610    437          1

[611 rows x 2 columns]

=== PHYSICS ===

     topic  doc_count
0       -1      92099
1      209       1358
2       50       1110
3      406        856
4       68        777
..     ...        ...
493    398          1
494    237          1
495    174          1
496    433          1
497    494          1

[498 rows x 2 columns]

## Tuning Loop

Grid search over `max_df × min_docs` for each subject.
Reuses the base assignment DataFrames from modeling checkpoints.

In [8]:
all_tuning_results = []

for subject in LIST_SUBJECT:
    if subject not in all_base_assignments:
        print(f"\nSkipping {subject} (no base assignment)")
        continue

    print(f"\n{'='*60}")
    print(f"TUNING: {subject.upper()}")
    print(f"{'='*60}")

    base_df = all_base_assignments[subject]
    texts = all_data[subject]["text"].fillna("").tolist()
    best_model = BEST_MODEL_MAP[subject]

    combos = list(product(MAX_DF_VALUES, MIN_DOCS_VALUES))
    best_tq, best_config = -1, None
    previous_n_topics = 0
    previous_metrics = {}
    prev_max_df = 0.5

    for max_df, min_docs in tqdm(combos, desc=f"Tuning {subject}"):
        ckpt_name = f"tuning_{best_model}_maxdf{max_df}_mindocs{min_docs}"

        # Check if already computed
        ckpt = load_checkpoint(ckpt_name, subject)
        if ckpt:
            metrics = ckpt["metrics"]
            n_topics = ckpt["n_topics"]
        else:
            # Apply filtering with current min_docs
            df_filtered = filter_and_reindex_topics(base_df, min_docs=min_docs)
            n_topics = df_filtered["topic_id"].nunique()

            if n_topics == 0:
                print(f"  max_df={max_df}, min_docs={min_docs}: 0 topics, skipping")
                metrics = {"coherence": 0.0, "irbo": 0.0, "topic_quality": 0.0}
            else:
                # Compute coherence with current max_df
                if previous_n_topics == n_topics and prev_max_df == max_df:
                    metrics = previous_metrics
                else:
                    metrics = compute_coherence_irbo(df_filtered, texts, max_df=max_df)
                previous_n_topics = n_topics
                previous_metrics = metrics
                prev_max_df = max_df

            save_checkpoint(
                {"metrics": metrics, "n_topics": n_topics,
                 "max_df": max_df, "min_docs": min_docs},
                ckpt_name, subject
            )

        row = {
            "subject": subject,
            "best_model": best_model,
            "max_df": max_df,
            "min_docs": min_docs,
            "n_topics": n_topics,
            "coherence": metrics["coherence"],
            "irbo": metrics["irbo"],
            "topic_quality": metrics["topic_quality"],
        }
        all_tuning_results.append(row)

        if metrics["topic_quality"] > best_tq:
            best_tq = metrics["topic_quality"]
            best_config = row

        tqdm.write(
            f"  max_df={max_df:.1f}  min_docs={min_docs:3d}  "
            f"topics={n_topics:3d}  C_v={metrics['coherence']:.4f}  "
            f"IRBO={metrics['irbo']:.4f}  TQ={metrics['topic_quality']:.4f}"
        )

    print(f"\n  BEST for {subject}: max_df={best_config['max_df']}, "
          f"min_docs={best_config['min_docs']}, TQ={best_tq:.4f}")

tuning_df = pd.DataFrame(all_tuning_results)
print(f"\nTotal results: {len(tuning_df)}")

============================================================
TUNING: CS
============================================================

Tuning cs:   2%|▏         | 1/42 [01:46<1:13:02, 106.90s/it]

  Checkpoint saved: ../../../../models/topicGpt/cs/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.5_mindocs10.pkl
  max_df=0.5  min_docs= 10  topics=576  C_v=0.6227  IRBO=0.9920  TQ=0.7651

Tuning cs:   5%|▍         | 2/42 [03:26<1:08:28, 102.71s/it]

  Checkpoint saved: ../../../../models/topicGpt/cs/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.5_mindocs25.pkl
  max_df=0.5  min_docs= 25  topics=508  C_v=0.6348  IRBO=0.9918  TQ=0.7741

Tuning cs:   7%|▋         | 3/42 [04:59<1:03:42, 98.01s/it]

  Checkpoint saved: ../../../../models/topicGpt/cs/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.5_mindocs50.pkl
  max_df=0.5  min_docs= 50  topics=384  C_v=0.6522  IRBO=0.9926  TQ=0.7872

Tuning cs:  10%|▉         | 4/42 [06:17<57:15, 90.40s/it]

  Checkpoint saved: ../../../../models/topicGpt/cs/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.5_mindocs100.pkl
  max_df=0.5  min_docs=100  topics=261  C_v=0.6729  IRBO=0.9935  TQ=0.8024

Tuning cs:  12%|█▏        | 5/42 [07:26<50:53, 82.53s/it]

  Checkpoint saved: ../../../../models/topicGpt/cs/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.5_mindocs150.pkl
  max_df=0.5  min_docs=150  topics=185  C_v=0.6786  IRBO=0.9938  TQ=0.8065

Tuning cs:  14%|█▍        | 6/42 [08:28<45:17, 75.50s/it]

  Checkpoint saved: ../../../../models/topicGpt/cs/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.5_mindocs200.pkl
  max_df=0.5  min_docs=200  topics=138  C_v=0.6795  IRBO=0.9946  TQ=0.8074

Tuning cs:  17%|█▋        | 7/42 [09:26<40:40, 69.72s/it]

  Checkpoint saved: ../../../../models/topicGpt/cs/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.5_mindocs250.pkl
  max_df=0.5  min_docs=250  topics=118  C_v=0.6784  IRBO=0.9947  TQ=0.8067

Tuning cs:  19%|█▉        | 8/42 [11:18<47:10, 83.24s/it]

  Checkpoint saved: ../../../../models/topicGpt/cs/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.6_mindocs10.pkl
  max_df=0.6  min_docs= 10  topics=576  C_v=0.6313  IRBO=0.9903  TQ=0.7710

Tuning cs:  21%|██▏       | 9/42 [12:58<48:41, 88.53s/it]

  Checkpoint saved: ../../../../models/topicGpt/cs/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.6_mindocs25.pkl
  max_df=0.6  min_docs= 25  topics=508  C_v=0.6466  IRBO=0.9904  TQ=0.7824

Tuning cs:  24%|██▍       | 10/42 [14:29<47:38, 89.32s/it]

  Checkpoint saved: ../../../../models/topicGpt/cs/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.6_mindocs50.pkl
  max_df=0.6  min_docs= 50  topics=384  C_v=0.6591  IRBO=0.9913  TQ=0.7918

Tuning cs:  26%|██▌       | 11/42 [15:48<44:34, 86.27s/it]

  Checkpoint saved: ../../../../models/topicGpt/cs/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.6_mindocs100.pkl
  max_df=0.6  min_docs=100  topics=261  C_v=0.6833  IRBO=0.9917  TQ=0.8091

Tuning cs:  29%|██▊       | 12/42 [16:57<40:28, 80.93s/it]

  Checkpoint saved: ../../../../models/topicGpt/cs/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.6_mindocs150.pkl
  max_df=0.6  min_docs=150  topics=185  C_v=0.6886  IRBO=0.9926  TQ=0.8131

Tuning cs:  31%|███       | 13/42 [17:59<36:15, 75.03s/it]

  Checkpoint saved: ../../../../models/topicGpt/cs/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.6_mindocs200.pkl
  max_df=0.6  min_docs=200  topics=138  C_v=0.6925  IRBO=0.9930  TQ=0.8159

Tuning cs:  33%|███▎      | 14/42 [18:58<32:52, 70.43s/it]

  Checkpoint saved: ../../../../models/topicGpt/cs/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.6_mindocs250.pkl
  max_df=0.6  min_docs=250  topics=118  C_v=0.6918  IRBO=0.9929  TQ=0.8154

Tuning cs:  36%|███▌      | 15/42 [20:51<37:25, 83.17s/it]

  Checkpoint saved: ../../../../models/topicGpt/cs/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.7_mindocs10.pkl
  max_df=0.7  min_docs= 10  topics=576  C_v=0.6339  IRBO=0.9892  TQ=0.7727

Tuning cs:  38%|███▊      | 16/42 [22:29<38:01, 87.74s/it]

  Checkpoint saved: ../../../../models/topicGpt/cs/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.7_mindocs25.pkl
  max_df=0.7  min_docs= 25  topics=508  C_v=0.6516  IRBO=0.9882  TQ=0.7853

Tuning cs:  40%|████      | 17/42 [23:58<36:43, 88.13s/it]

  Checkpoint saved: ../../../../models/topicGpt/cs/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.7_mindocs50.pkl
  max_df=0.7  min_docs= 50  topics=384  C_v=0.6686  IRBO=0.9884  TQ=0.7976

Tuning cs:  43%|████▎     | 18/42 [25:16<33:58, 84.95s/it]

  Checkpoint saved: ../../../../models/topicGpt/cs/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.7_mindocs100.pkl
  max_df=0.7  min_docs=100  topics=261  C_v=0.6881  IRBO=0.9900  TQ=0.8119

Tuning cs:  45%|████▌     | 19/42 [26:25<30:40, 80.03s/it]

  Checkpoint saved: ../../../../models/topicGpt/cs/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.7_mindocs150.pkl
  max_df=0.7  min_docs=150  topics=185  C_v=0.6943  IRBO=0.9907  TQ=0.8164

Tuning cs:  48%|████▊     | 20/42 [27:26<27:20, 74.58s/it]

  Checkpoint saved: ../../../../models/topicGpt/cs/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.7_mindocs200.pkl
  max_df=0.7  min_docs=200  topics=138  C_v=0.7020  IRBO=0.9918  TQ=0.8221

Tuning cs:  50%|█████     | 21/42 [28:24<24:21, 69.60s/it]

  Checkpoint saved: ../../../../models/topicGpt/cs/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.7_mindocs250.pkl
  max_df=0.7  min_docs=250  topics=118  C_v=0.7002  IRBO=0.9916  TQ=0.8208

Tuning cs:  52%|█████▏    | 22/42 [30:20<27:47, 83.39s/it]

  Checkpoint saved: ../../../../models/topicGpt/cs/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.8_mindocs10.pkl
  max_df=0.8  min_docs= 10  topics=576  C_v=0.6302  IRBO=0.9874  TQ=0.7694

Tuning cs:  55%|█████▍    | 23/42 [31:59<27:54, 88.14s/it]

  Checkpoint saved: ../../../../models/topicGpt/cs/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.8_mindocs25.pkl
  max_df=0.8  min_docs= 25  topics=508  C_v=0.6509  IRBO=0.9868  TQ=0.7844

Tuning cs:  57%|█████▋    | 24/42 [33:27<26:23, 88.00s/it]

  Checkpoint saved: ../../../../models/topicGpt/cs/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.8_mindocs50.pkl
  max_df=0.8  min_docs= 50  topics=384  C_v=0.6714  IRBO=0.9866  TQ=0.7991

Tuning cs:  60%|█████▉    | 25/42 [34:42<23:51, 84.19s/it]

  Checkpoint saved: ../../../../models/topicGpt/cs/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.8_mindocs100.pkl
  max_df=0.8  min_docs=100  topics=261  C_v=0.6937  IRBO=0.9869  TQ=0.8147

Tuning cs:  62%|██████▏   | 26/42 [35:46<20:51, 78.21s/it]

  Checkpoint saved: ../../../../models/topicGpt/cs/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.8_mindocs150.pkl
  max_df=0.8  min_docs=150  topics=185  C_v=0.7012  IRBO=0.9854  TQ=0.8193

Tuning cs:  64%|██████▍   | 27/42 [36:47<18:13, 72.90s/it]

  Checkpoint saved: ../../../../models/topicGpt/cs/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.8_mindocs200.pkl
  max_df=0.8  min_docs=200  topics=138  C_v=0.7095  IRBO=0.9893  TQ=0.8264

Tuning cs:  67%|██████▋   | 28/42 [37:45<15:56, 68.31s/it]

  Checkpoint saved: ../../../../models/topicGpt/cs/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.8_mindocs250.pkl
  max_df=0.8  min_docs=250  topics=118  C_v=0.7086  IRBO=0.9889  TQ=0.8256

Tuning cs:  69%|██████▉   | 29/42 [39:40<17:50, 82.35s/it]

  Checkpoint saved: ../../../../models/topicGpt/cs/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.9_mindocs10.pkl
  max_df=0.9  min_docs= 10  topics=576  C_v=0.6275  IRBO=0.9861  TQ=0.7670

Tuning cs:  71%|███████▏  | 30/42 [41:20<17:34, 87.88s/it]

  Checkpoint saved: ../../../../models/topicGpt/cs/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.9_mindocs25.pkl
  max_df=0.9  min_docs= 25  topics=508  C_v=0.6473  IRBO=0.9850  TQ=0.7812

Tuning cs:  74%|███████▍  | 31/42 [42:50<16:13, 88.48s/it]

  Checkpoint saved: ../../../../models/topicGpt/cs/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.9_mindocs50.pkl
  max_df=0.9  min_docs= 50  topics=384  C_v=0.6653  IRBO=0.9834  TQ=0.7936

Tuning cs:  76%|███████▌  | 32/42 [44:04<14:01, 84.11s/it]

  Checkpoint saved: ../../../../models/topicGpt/cs/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.9_mindocs100.pkl
  max_df=0.9  min_docs=100  topics=261  C_v=0.6938  IRBO=0.9850  TQ=0.8142

Tuning cs:  79%|███████▊  | 33/42 [45:08<11:41, 77.91s/it]

  Checkpoint saved: ../../../../models/topicGpt/cs/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.9_mindocs150.pkl
  max_df=0.9  min_docs=150  topics=185  C_v=0.7030  IRBO=0.9832  TQ=0.8198

Tuning cs:  81%|████████  | 34/42 [46:06<09:36, 72.00s/it]

  Checkpoint saved: ../../../../models/topicGpt/cs/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.9_mindocs200.pkl
  max_df=0.9  min_docs=200  topics=138  C_v=0.7135  IRBO=0.9784  TQ=0.8252

Tuning cs:  83%|████████▎ | 35/42 [47:02<07:50, 67.19s/it]

  Checkpoint saved: ../../../../models/topicGpt/cs/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.9_mindocs250.pkl
  max_df=0.9  min_docs=250  topics=118  C_v=0.7116  IRBO=0.9759  TQ=0.8231

Tuning cs:  86%|████████▌ | 36/42 [49:02<08:18, 83.12s/it]

  Checkpoint saved: ../../../../models/topicGpt/cs/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf1.0_mindocs10.pkl
  max_df=1.0  min_docs= 10  topics=576  C_v=0.5990  IRBO=0.9756  TQ=0.7423

Tuning cs:  88%|████████▊ | 37/42 [50:47<07:27, 89.53s/it]

  Checkpoint saved: ../../../../models/topicGpt/cs/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf1.0_mindocs25.pkl
  max_df=1.0  min_docs= 25  topics=508  C_v=0.6125  IRBO=0.9720  TQ=0.7514

Tuning cs:  90%|█████████ | 38/42 [52:18<06:00, 90.21s/it]

  Checkpoint saved: ../../../../models/topicGpt/cs/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf1.0_mindocs50.pkl
  max_df=1.0  min_docs= 50  topics=384  C_v=0.6219  IRBO=0.9643  TQ=0.7562

Tuning cs:  93%|█████████▎| 39/42 [53:36<04:19, 86.43s/it]

  Checkpoint saved: ../../../../models/topicGpt/cs/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf1.0_mindocs100.pkl
  max_df=1.0  min_docs=100  topics=261  C_v=0.6300  IRBO=0.9530  TQ=0.7586

Tuning cs:  95%|█████████▌| 40/42 [54:43<02:41, 80.60s/it]

  Checkpoint saved: ../../../../models/topicGpt/cs/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf1.0_mindocs150.pkl
  max_df=1.0  min_docs=150  topics=185  C_v=0.6296  IRBO=0.9448  TQ=0.7557

Tuning cs:  98%|█████████▊| 41/42 [55:44<01:14, 74.66s/it]

  Checkpoint saved: ../../../../models/topicGpt/cs/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf1.0_mindocs200.pkl
  max_df=1.0  min_docs=200  topics=138  C_v=0.6298  IRBO=0.9328  TQ=0.7519

Tuning cs: 100%|██████████| 42/42 [56:42<00:00, 81.00s/it]

  Checkpoint saved: ../../../../models/topicGpt/cs/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf1.0_mindocs250.pkl
  max_df=1.0  min_docs=250  topics=118  C_v=0.6258  IRBO=0.9245  TQ=0.7464

  BEST for cs: max_df=0.8, min_docs=200, TQ=0.8264

============================================================
TUNING: MATH
============================================================

Tuning math:   2%|▏         | 1/42 [01:07<45:47, 67.01s/it]

  Checkpoint saved: ../../../../models/topicGpt/math/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.5_mindocs10.pkl
  max_df=0.5  min_docs= 10  topics=565  C_v=0.5921  IRBO=0.9937  TQ=0.7420

Tuning math:   5%|▍         | 2/42 [02:04<41:03, 61.58s/it]

  Checkpoint saved: ../../../../models/topicGpt/math/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.5_mindocs25.pkl
  max_df=0.5  min_docs= 25  topics=497  C_v=0.6094  IRBO=0.9937  TQ=0.7555

Tuning math:   7%|▋         | 3/42 [02:56<37:03, 57.02s/it]

  Checkpoint saved: ../../../../models/topicGpt/math/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.5_mindocs50.pkl
  max_df=0.5  min_docs= 50  topics=391  C_v=0.6347  IRBO=0.9935  TQ=0.7745

Tuning math:  10%|▉         | 4/42 [03:39<32:33, 51.40s/it]

  Checkpoint saved: ../../../../models/topicGpt/math/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.5_mindocs100.pkl
  max_df=0.5  min_docs=100  topics=251  C_v=0.6519  IRBO=0.9941  TQ=0.7875

Tuning math:  12%|█▏        | 5/42 [04:14<28:08, 45.62s/it]

  Checkpoint saved: ../../../../models/topicGpt/math/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.5_mindocs150.pkl
  max_df=0.5  min_docs=150  topics=175  C_v=0.6605  IRBO=0.9942  TQ=0.7938

Tuning math:  14%|█▍        | 6/42 [04:45<24:23, 40.64s/it]

  Checkpoint saved: ../../../../models/topicGpt/math/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.5_mindocs200.pkl
  max_df=0.5  min_docs=200  topics=124  C_v=0.6830  IRBO=0.9941  TQ=0.8097

Tuning math:  17%|█▋        | 7/42 [05:12<21:09, 36.26s/it]

  Checkpoint saved: ../../../../models/topicGpt/math/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.5_mindocs250.pkl
  max_df=0.5  min_docs=250  topics= 90  C_v=0.6916  IRBO=0.9932  TQ=0.8154

Tuning math:  19%|█▉        | 8/42 [06:18<25:50, 45.62s/it]

  Checkpoint saved: ../../../../models/topicGpt/math/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.6_mindocs10.pkl
  max_df=0.6  min_docs= 10  topics=565  C_v=0.5981  IRBO=0.9919  TQ=0.7462

Tuning math:  21%|██▏       | 9/42 [07:16<27:09, 49.37s/it]

  Checkpoint saved: ../../../../models/topicGpt/math/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.6_mindocs25.pkl
  max_df=0.6  min_docs= 25  topics=497  C_v=0.6161  IRBO=0.9913  TQ=0.7599

Tuning math:  24%|██▍       | 10/42 [08:07<26:39, 49.99s/it]

  Checkpoint saved: ../../../../models/topicGpt/math/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.6_mindocs50.pkl
  max_df=0.6  min_docs= 50  topics=391  C_v=0.6426  IRBO=0.9922  TQ=0.7800

Tuning math:  26%|██▌       | 11/42 [08:50<24:39, 47.74s/it]

  Checkpoint saved: ../../../../models/topicGpt/math/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.6_mindocs100.pkl
  max_df=0.6  min_docs=100  topics=251  C_v=0.6669  IRBO=0.9923  TQ=0.7977

Tuning math:  29%|██▊       | 12/42 [09:24<21:52, 43.74s/it]

  Checkpoint saved: ../../../../models/topicGpt/math/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.6_mindocs150.pkl
  max_df=0.6  min_docs=150  topics=175  C_v=0.6755  IRBO=0.9916  TQ=0.8036

Tuning math:  31%|███       | 13/42 [09:54<19:09, 39.62s/it]

  Checkpoint saved: ../../../../models/topicGpt/math/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.6_mindocs200.pkl
  max_df=0.6  min_docs=200  topics=124  C_v=0.6957  IRBO=0.9932  TQ=0.8182

Tuning math:  33%|███▎      | 14/42 [10:22<16:44, 35.88s/it]

  Checkpoint saved: ../../../../models/topicGpt/math/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.6_mindocs250.pkl
  max_df=0.6  min_docs=250  topics= 90  C_v=0.7064  IRBO=0.9927  TQ=0.8254

Tuning math:  36%|███▌      | 15/42 [11:26<20:00, 44.45s/it]

  Checkpoint saved: ../../../../models/topicGpt/math/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.7_mindocs10.pkl
  max_df=0.7  min_docs= 10  topics=565  C_v=0.6080  IRBO=0.9893  TQ=0.7532

Tuning math:  38%|███▊      | 16/42 [12:24<21:00, 48.49s/it]

  Checkpoint saved: ../../../../models/topicGpt/math/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.7_mindocs25.pkl
  max_df=0.7  min_docs= 25  topics=497  C_v=0.6207  IRBO=0.9896  TQ=0.7629

Tuning math:  40%|████      | 17/42 [13:15<20:33, 49.36s/it]

  Checkpoint saved: ../../../../models/topicGpt/math/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.7_mindocs50.pkl
  max_df=0.7  min_docs= 50  topics=391  C_v=0.6501  IRBO=0.9892  TQ=0.7846

Tuning math:  43%|████▎     | 18/42 [13:57<18:48, 47.03s/it]

  Checkpoint saved: ../../../../models/topicGpt/math/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.7_mindocs100.pkl
  max_df=0.7  min_docs=100  topics=251  C_v=0.6775  IRBO=0.9873  TQ=0.8035

Tuning math:  45%|████▌     | 19/42 [14:31<16:31, 43.09s/it]

  Checkpoint saved: ../../../../models/topicGpt/math/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.7_mindocs150.pkl
  max_df=0.7  min_docs=150  topics=175  C_v=0.6862  IRBO=0.9902  TQ=0.8107

Tuning math:  48%|████▊     | 20/42 [15:00<14:14, 38.86s/it]

  Checkpoint saved: ../../../../models/topicGpt/math/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.7_mindocs200.pkl
  max_df=0.7  min_docs=200  topics=124  C_v=0.7062  IRBO=0.9893  TQ=0.8241

Tuning math:  50%|█████     | 21/42 [15:26<12:17, 35.10s/it]

  Checkpoint saved: ../../../../models/topicGpt/math/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.7_mindocs250.pkl
  max_df=0.7  min_docs=250  topics= 90  C_v=0.7174  IRBO=0.9875  TQ=0.8311

Tuning math:  52%|█████▏    | 22/42 [16:30<14:37, 43.86s/it]

  Checkpoint saved: ../../../../models/topicGpt/math/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.8_mindocs10.pkl
  max_df=0.8  min_docs= 10  topics=565  C_v=0.6147  IRBO=0.9891  TQ=0.7582

Tuning math:  55%|█████▍    | 23/42 [17:27<15:06, 47.70s/it]

  Checkpoint saved: ../../../../models/topicGpt/math/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.8_mindocs25.pkl
  max_df=0.8  min_docs= 25  topics=497  C_v=0.6299  IRBO=0.9882  TQ=0.7694

Tuning math:  57%|█████▋    | 24/42 [18:17<14:30, 48.39s/it]

  Checkpoint saved: ../../../../models/topicGpt/math/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.8_mindocs50.pkl
  max_df=0.8  min_docs= 50  topics=391  C_v=0.6572  IRBO=0.9869  TQ=0.7890

Tuning math:  60%|█████▉    | 25/42 [18:57<12:59, 45.85s/it]

  Checkpoint saved: ../../../../models/topicGpt/math/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.8_mindocs100.pkl
  max_df=0.8  min_docs=100  topics=251  C_v=0.6794  IRBO=0.9868  TQ=0.8047

Tuning math:  62%|██████▏   | 26/42 [19:30<11:13, 42.12s/it]

  Checkpoint saved: ../../../../models/topicGpt/math/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.8_mindocs150.pkl
  max_df=0.8  min_docs=150  topics=175  C_v=0.6989  IRBO=0.9845  TQ=0.8174

Tuning math:  64%|██████▍   | 27/42 [19:59<09:33, 38.21s/it]

  Checkpoint saved: ../../../../models/topicGpt/math/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.8_mindocs200.pkl
  max_df=0.8  min_docs=200  topics=124  C_v=0.7162  IRBO=0.9835  TQ=0.8288

Tuning math:  67%|██████▋   | 28/42 [20:25<08:02, 34.44s/it]

  Checkpoint saved: ../../../../models/topicGpt/math/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.8_mindocs250.pkl
  max_df=0.8  min_docs=250  topics= 90  C_v=0.7233  IRBO=0.9821  TQ=0.8330

Tuning math:  69%|██████▉   | 29/42 [21:27<09:17, 42.85s/it]

  Checkpoint saved: ../../../../models/topicGpt/math/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.9_mindocs10.pkl
  max_df=0.9  min_docs= 10  topics=565  C_v=0.6045  IRBO=0.9824  TQ=0.7484

Tuning math:  71%|███████▏  | 30/42 [22:24<09:23, 46.98s/it]

  Checkpoint saved: ../../../../models/topicGpt/math/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.9_mindocs25.pkl
  max_df=0.9  min_docs= 25  topics=497  C_v=0.6332  IRBO=0.9876  TQ=0.7716

Tuning math:  74%|███████▍  | 31/42 [23:15<08:49, 48.10s/it]

  Checkpoint saved: ../../../../models/topicGpt/math/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.9_mindocs50.pkl
  max_df=0.9  min_docs= 50  topics=391  C_v=0.6581  IRBO=0.9861  TQ=0.7894

Tuning math:  76%|███████▌  | 32/42 [23:55<07:37, 45.78s/it]

  Checkpoint saved: ../../../../models/topicGpt/math/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.9_mindocs100.pkl
  max_df=0.9  min_docs=100  topics=251  C_v=0.6855  IRBO=0.9831  TQ=0.8077

Tuning math:  79%|███████▊  | 33/42 [24:29<06:19, 42.21s/it]

  Checkpoint saved: ../../../../models/topicGpt/math/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.9_mindocs150.pkl
  max_df=0.9  min_docs=150  topics=175  C_v=0.7008  IRBO=0.9817  TQ=0.8178

Tuning math:  81%|████████  | 34/42 [24:58<05:05, 38.17s/it]

  Checkpoint saved: ../../../../models/topicGpt/math/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.9_mindocs200.pkl
  max_df=0.9  min_docs=200  topics=124  C_v=0.7194  IRBO=0.9827  TQ=0.8306

Tuning math:  83%|████████▎ | 35/42 [25:22<03:58, 34.13s/it]

  Checkpoint saved: ../../../../models/topicGpt/math/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf0.9_mindocs250.pkl
  max_df=0.9  min_docs=250  topics= 90  C_v=0.7280  IRBO=0.9809  TQ=0.8358

Tuning math:  86%|████████▌ | 36/42 [26:24<04:14, 42.43s/it]

  Checkpoint saved: ../../../../models/topicGpt/math/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf1.0_mindocs10.pkl
  max_df=1.0  min_docs= 10  topics=565  C_v=0.6041  IRBO=0.9822  TQ=0.7481

Tuning math:  88%|████████▊ | 37/42 [27:19<03:50, 46.11s/it]

  Checkpoint saved: ../../../../models/topicGpt/math/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf1.0_mindocs25.pkl
  max_df=1.0  min_docs= 25  topics=497  C_v=0.6204  IRBO=0.9803  TQ=0.7599

Tuning math:  90%|█████████ | 38/42 [28:09<03:08, 47.22s/it]

  Checkpoint saved: ../../../../models/topicGpt/math/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf1.0_mindocs50.pkl
  max_df=1.0  min_docs= 50  topics=391  C_v=0.6445  IRBO=0.9776  TQ=0.7769

Tuning math:  93%|█████████▎| 39/42 [28:47<02:13, 44.62s/it]

  Checkpoint saved: ../../../../models/topicGpt/math/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf1.0_mindocs100.pkl
  max_df=1.0  min_docs=100  topics=251  C_v=0.6604  IRBO=0.9711  TQ=0.7861

Tuning math:  95%|█████████▌| 40/42 [29:20<01:22, 41.11s/it]

  Checkpoint saved: ../../../../models/topicGpt/math/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf1.0_mindocs150.pkl
  max_df=1.0  min_docs=150  topics=175  C_v=0.6704  IRBO=0.9675  TQ=0.7920

Tuning math:  98%|█████████▊| 41/42 [29:49<00:37, 37.48s/it]

  Checkpoint saved: ../../../../models/topicGpt/math/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf1.0_mindocs200.pkl
  max_df=1.0  min_docs=200  topics=124  C_v=0.6805  IRBO=0.9651  TQ=0.7982

Tuning math: 100%|██████████| 42/42 [30:14<00:00, 43.21s/it]

  Checkpoint saved: ../../../../models/topicGpt/math/tuning_sentence_transformers_all_MiniLM_L6_v2_maxdf1.0_mindocs250.pkl
  max_df=1.0  min_docs=250  topics= 90  C_v=0.6915  IRBO=0.9648  TQ=0.8056

  BEST for math: max_df=0.9, min_docs=250, TQ=0.8358

============================================================
TUNING: PHYSICS
============================================================

Tuning physics:   2%|▏         | 1/42 [01:17<52:54, 77.44s/it]

  Checkpoint saved: ../../../../models/topicGpt/physics/tuning_all_distilroberta_v1_maxdf0.5_mindocs10.pkl
  max_df=0.5  min_docs= 10  topics=432  C_v=0.6528  IRBO=0.9926  TQ=0.7876

Tuning physics:   5%|▍         | 2/42 [02:25<47:53, 71.83s/it]

  Checkpoint saved: ../../../../models/topicGpt/physics/tuning_all_distilroberta_v1_maxdf0.5_mindocs25.pkl
  max_df=0.5  min_docs= 25  topics=368  C_v=0.6753  IRBO=0.9922  TQ=0.8037

Tuning physics:   7%|▋         | 3/42 [03:24<43:03, 66.24s/it]

  Checkpoint saved: ../../../../models/topicGpt/physics/tuning_all_distilroberta_v1_maxdf0.5_mindocs50.pkl
  max_df=0.5  min_docs= 50  topics=278  C_v=0.6921  IRBO=0.9916  TQ=0.8152

Tuning physics:  10%|▉         | 4/42 [04:15<37:55, 59.88s/it]

  Checkpoint saved: ../../../../models/topicGpt/physics/tuning_all_distilroberta_v1_maxdf0.5_mindocs100.pkl
  max_df=0.5  min_docs=100  topics=178  C_v=0.7024  IRBO=0.9914  TQ=0.8222

Tuning physics:  12%|█▏        | 5/42 [04:53<32:07, 52.08s/it]

  Checkpoint saved: ../../../../models/topicGpt/physics/tuning_all_distilroberta_v1_maxdf0.5_mindocs150.pkl
  max_df=0.5  min_docs=150  topics=101  C_v=0.7132  IRBO=0.9909  TQ=0.8294

Tuning physics:  14%|█▍        | 6/42 [05:27<27:35, 45.98s/it]

  Checkpoint saved: ../../../../models/topicGpt/physics/tuning_all_distilroberta_v1_maxdf0.5_mindocs200.pkl
  max_df=0.5  min_docs=200  topics= 74  C_v=0.7318  IRBO=0.9890  TQ=0.8412

Tuning physics:  17%|█▋        | 7/42 [05:55<23:28, 40.25s/it]

  Checkpoint saved: ../../../../models/topicGpt/physics/tuning_all_distilroberta_v1_maxdf0.5_mindocs250.pkl
  max_df=0.5  min_docs=250  topics= 50  C_v=0.7214  IRBO=0.9844  TQ=0.8326

Tuning physics:  19%|█▉        | 8/42 [07:12<29:25, 51.93s/it]

  Checkpoint saved: ../../../../models/topicGpt/physics/tuning_all_distilroberta_v1_maxdf0.6_mindocs10.pkl
  max_df=0.6  min_docs= 10  topics=432  C_v=0.6576  IRBO=0.9907  TQ=0.7905

Tuning physics:  21%|██▏       | 9/42 [08:20<31:14, 56.82s/it]

  Checkpoint saved: ../../../../models/topicGpt/physics/tuning_all_distilroberta_v1_maxdf0.6_mindocs25.pkl
  max_df=0.6  min_docs= 25  topics=368  C_v=0.6791  IRBO=0.9914  TQ=0.8060

Tuning physics:  24%|██▍       | 10/42 [09:18<30:33, 57.31s/it]

  Checkpoint saved: ../../../../models/topicGpt/physics/tuning_all_distilroberta_v1_maxdf0.6_mindocs50.pkl
  max_df=0.6  min_docs= 50  topics=278  C_v=0.6963  IRBO=0.9907  TQ=0.8178

Tuning physics:  26%|██▌       | 11/42 [10:07<28:13, 54.63s/it]

  Checkpoint saved: ../../../../models/topicGpt/physics/tuning_all_distilroberta_v1_maxdf0.6_mindocs100.pkl
  max_df=0.6  min_docs=100  topics=178  C_v=0.7079  IRBO=0.9908  TQ=0.8258

Tuning physics:  29%|██▊       | 12/42 [10:45<24:52, 49.75s/it]

  Checkpoint saved: ../../../../models/topicGpt/physics/tuning_all_distilroberta_v1_maxdf0.6_mindocs150.pkl
  max_df=0.6  min_docs=150  topics=101  C_v=0.7269  IRBO=0.9894  TQ=0.8380

Tuning physics:  31%|███       | 13/42 [11:18<21:35, 44.69s/it]

  Checkpoint saved: ../../../../models/topicGpt/physics/tuning_all_distilroberta_v1_maxdf0.6_mindocs200.pkl
  max_df=0.6  min_docs=200  topics= 74  C_v=0.7382  IRBO=0.9887  TQ=0.8453

Tuning physics:  33%|███▎      | 14/42 [11:47<18:34, 39.79s/it]

  Checkpoint saved: ../../../../models/topicGpt/physics/tuning_all_distilroberta_v1_maxdf0.6_mindocs250.pkl
  max_df=0.6  min_docs=250  topics= 50  C_v=0.7316  IRBO=0.9835  TQ=0.8391

Tuning physics:  36%|███▌      | 15/42 [13:03<22:48, 50.67s/it]

  Checkpoint saved: ../../../../models/topicGpt/physics/tuning_all_distilroberta_v1_maxdf0.7_mindocs10.pkl
  max_df=0.7  min_docs= 10  topics=432  C_v=0.6597  IRBO=0.9872  TQ=0.7909

Tuning physics:  38%|███▊      | 16/42 [14:11<24:13, 55.91s/it]

  Checkpoint saved: ../../../../models/topicGpt/physics/tuning_all_distilroberta_v1_maxdf0.7_mindocs25.pkl
  max_df=0.7  min_docs= 25  topics=368  C_v=0.6814  IRBO=0.9887  TQ=0.8068

Tuning physics:  40%|████      | 17/42 [15:09<23:36, 56.68s/it]

  Checkpoint saved: ../../../../models/topicGpt/physics/tuning_all_distilroberta_v1_maxdf0.7_mindocs50.pkl
  max_df=0.7  min_docs= 50  topics=278  C_v=0.7003  IRBO=0.9888  TQ=0.8199

Tuning physics:  43%|████▎     | 18/42 [15:58<21:41, 54.24s/it]

  Checkpoint saved: ../../../../models/topicGpt/physics/tuning_all_distilroberta_v1_maxdf0.7_mindocs100.pkl
  max_df=0.7  min_docs=100  topics=178  C_v=0.7145  IRBO=0.9892  TQ=0.8297

Tuning physics:  45%|████▌     | 19/42 [16:35<18:50, 49.16s/it]

  Checkpoint saved: ../../../../models/topicGpt/physics/tuning_all_distilroberta_v1_maxdf0.7_mindocs150.pkl
  max_df=0.7  min_docs=150  topics=101  C_v=0.7283  IRBO=0.9879  TQ=0.8385

Tuning physics:  48%|████▊     | 20/42 [17:08<16:12, 44.22s/it]

  Checkpoint saved: ../../../../models/topicGpt/physics/tuning_all_distilroberta_v1_maxdf0.7_mindocs200.pkl
  max_df=0.7  min_docs=200  topics= 74  C_v=0.7398  IRBO=0.9873  TQ=0.8458

Tuning physics:  50%|█████     | 21/42 [17:37<13:50, 39.56s/it]

  Checkpoint saved: ../../../../models/topicGpt/physics/tuning_all_distilroberta_v1_maxdf0.7_mindocs250.pkl
  max_df=0.7  min_docs=250  topics= 50  C_v=0.7383  IRBO=0.9810  TQ=0.8425

Tuning physics:  52%|█████▏    | 22/42 [18:55<17:02, 51.15s/it]

  Checkpoint saved: ../../../../models/topicGpt/physics/tuning_all_distilroberta_v1_maxdf0.8_mindocs10.pkl
  max_df=0.8  min_docs= 10  topics=432  C_v=0.6580  IRBO=0.9809  TQ=0.7877

Tuning physics:  55%|█████▍    | 23/42 [20:02<17:40, 55.82s/it]

  Checkpoint saved: ../../../../models/topicGpt/physics/tuning_all_distilroberta_v1_maxdf0.8_mindocs25.pkl
  max_df=0.8  min_docs= 25  topics=368  C_v=0.6803  IRBO=0.9797  TQ=0.8030

Tuning physics:  57%|█████▋    | 24/42 [20:59<16:51, 56.19s/it]

  Checkpoint saved: ../../../../models/topicGpt/physics/tuning_all_distilroberta_v1_maxdf0.8_mindocs50.pkl
  max_df=0.8  min_docs= 50  topics=278  C_v=0.6981  IRBO=0.9762  TQ=0.8140

Tuning physics:  60%|█████▉    | 25/42 [21:46<15:08, 53.44s/it]

  Checkpoint saved: ../../../../models/topicGpt/physics/tuning_all_distilroberta_v1_maxdf0.8_mindocs100.pkl
  max_df=0.8  min_docs=100  topics=178  C_v=0.7191  IRBO=0.9835  TQ=0.8308

Tuning physics:  62%|██████▏   | 26/42 [22:23<12:59, 48.70s/it]

  Checkpoint saved: ../../../../models/topicGpt/physics/tuning_all_distilroberta_v1_maxdf0.8_mindocs150.pkl
  max_df=0.8  min_docs=150  topics=101  C_v=0.7302  IRBO=0.9854  TQ=0.8388

Tuning physics:  64%|██████▍   | 27/42 [22:56<10:56, 43.79s/it]

  Checkpoint saved: ../../../../models/topicGpt/physics/tuning_all_distilroberta_v1_maxdf0.8_mindocs200.pkl
  max_df=0.8  min_docs=200  topics= 74  C_v=0.7406  IRBO=0.9835  TQ=0.8449

Tuning physics:  67%|██████▋   | 28/42 [23:24<09:08, 39.19s/it]

  Checkpoint saved: ../../../../models/topicGpt/physics/tuning_all_distilroberta_v1_maxdf0.8_mindocs250.pkl
  max_df=0.8  min_docs=250  topics= 50  C_v=0.7320  IRBO=0.9790  TQ=0.8377

Tuning physics:  69%|██████▉   | 29/42 [24:43<11:03, 51.02s/it]

  Checkpoint saved: ../../../../models/topicGpt/physics/tuning_all_distilroberta_v1_maxdf0.9_mindocs10.pkl
  max_df=0.9  min_docs= 10  topics=432  C_v=0.6591  IRBO=0.9810  TQ=0.7885

Tuning physics:  71%|███████▏  | 30/42 [25:51<11:13, 56.16s/it]

  Checkpoint saved: ../../../../models/topicGpt/physics/tuning_all_distilroberta_v1_maxdf0.9_mindocs25.pkl
  max_df=0.9  min_docs= 25  topics=368  C_v=0.6786  IRBO=0.9800  TQ=0.8019

Tuning physics:  74%|███████▍  | 31/42 [26:49<10:25, 56.87s/it]

  Checkpoint saved: ../../../../models/topicGpt/physics/tuning_all_distilroberta_v1_maxdf0.9_mindocs50.pkl
  max_df=0.9  min_docs= 50  topics=278  C_v=0.6945  IRBO=0.9770  TQ=0.8119

Tuning physics:  76%|███████▌  | 32/42 [27:35<08:56, 53.60s/it]

  Checkpoint saved: ../../../../models/topicGpt/physics/tuning_all_distilroberta_v1_maxdf0.9_mindocs100.pkl
  max_df=0.9  min_docs=100  topics=178  C_v=0.7154  IRBO=0.9713  TQ=0.8239

Tuning physics:  79%|███████▊  | 33/42 [28:12<07:17, 48.57s/it]

  Checkpoint saved: ../../../../models/topicGpt/physics/tuning_all_distilroberta_v1_maxdf0.9_mindocs150.pkl
  max_df=0.9  min_docs=150  topics=101  C_v=0.7330  IRBO=0.9746  TQ=0.8367

Tuning physics:  81%|████████  | 34/42 [28:44<05:49, 43.68s/it]

  Checkpoint saved: ../../../../models/topicGpt/physics/tuning_all_distilroberta_v1_maxdf0.9_mindocs200.pkl
  max_df=0.9  min_docs=200  topics= 74  C_v=0.7418  IRBO=0.9753  TQ=0.8427

Tuning physics:  83%|████████▎ | 35/42 [29:13<04:34, 39.20s/it]

  Checkpoint saved: ../../../../models/topicGpt/physics/tuning_all_distilroberta_v1_maxdf0.9_mindocs250.pkl
  max_df=0.9  min_docs=250  topics= 50  C_v=0.7294  IRBO=0.9695  TQ=0.8325

Tuning physics:  86%|████████▌ | 36/42 [30:32<05:06, 51.11s/it]

  Checkpoint saved: ../../../../models/topicGpt/physics/tuning_all_distilroberta_v1_maxdf1.0_mindocs10.pkl
  max_df=1.0  min_docs= 10  topics=432  C_v=0.6469  IRBO=0.9800  TQ=0.7793

Tuning physics:  88%|████████▊ | 37/42 [31:40<04:41, 56.29s/it]

  Checkpoint saved: ../../../../models/topicGpt/physics/tuning_all_distilroberta_v1_maxdf1.0_mindocs25.pkl
  max_df=1.0  min_docs= 25  topics=368  C_v=0.6646  IRBO=0.9782  TQ=0.7915

Tuning physics:  90%|█████████ | 38/42 [32:38<03:46, 56.66s/it]

  Checkpoint saved: ../../../../models/topicGpt/physics/tuning_all_distilroberta_v1_maxdf1.0_mindocs50.pkl
  max_df=1.0  min_docs= 50  topics=278  C_v=0.6754  IRBO=0.9750  TQ=0.7980

Tuning physics:  93%|█████████▎| 39/42 [33:27<02:43, 54.50s/it]

  Checkpoint saved: ../../../../models/topicGpt/physics/tuning_all_distilroberta_v1_maxdf1.0_mindocs100.pkl
  max_df=1.0  min_docs=100  topics=178  C_v=0.6822  IRBO=0.9698  TQ=0.8010

Tuning physics:  95%|█████████▌| 40/42 [34:06<01:39, 49.84s/it]

  Checkpoint saved: ../../../../models/topicGpt/physics/tuning_all_distilroberta_v1_maxdf1.0_mindocs150.pkl
  max_df=1.0  min_docs=150  topics=101  C_v=0.6871  IRBO=0.9658  TQ=0.8030

Tuning physics:  98%|█████████▊| 41/42 [34:42<00:45, 45.59s/it]

  Checkpoint saved: ../../../../models/topicGpt/physics/tuning_all_distilroberta_v1_maxdf1.0_mindocs200.pkl
  max_df=1.0  min_docs=200  topics= 74  C_v=0.6903  IRBO=0.9658  TQ=0.8052

Tuning physics: 100%|██████████| 42/42 [35:13<00:00, 50.32s/it]

  Checkpoint saved: ../../../../models/topicGpt/physics/tuning_all_distilroberta_v1_maxdf1.0_mindocs250.pkl
  max_df=1.0  min_docs=250  topics= 50  C_v=0.6831  IRBO=0.9586  TQ=0.7977

  BEST for physics: max_df=0.7, min_docs=200, TQ=0.8458

Total results: 126

## Results Summary

In [9]:
# Save full results CSV per subject
for subject in LIST_SUBJECT:
    subj_df = tuning_df[tuning_df["subject"] == subject]
    if len(subj_df) == 0:
        continue
    out_path = RESULT_DIR / subject / "tuning_results.csv"
    subj_df.to_csv(out_path, index=False)
    print(f"Saved: {out_path}")

# Also save combined results
combined_path = RESULT_DIR / "tuning_results_all.csv"
tuning_df.to_csv(combined_path, index=False)
print(f"\nCombined results saved: {combined_path}")

# Show best per subject
print(f"\n{'='*80}")
print(f"BEST CONFIGURATION PER SUBJECT")
print(f"{'='*80}")
for subject in LIST_SUBJECT:
    subj_df = tuning_df[tuning_df["subject"] == subject]
    if len(subj_df) == 0:
        continue
    best = subj_df.loc[subj_df["topic_quality"].idxmax()]
    print(f"\n{subject.upper()}:")
    print(f"  Model:    {best['best_model']}")
    print(f"  max_df:   {best['max_df']}")
    print(f"  min_docs: {int(best['min_docs'])}")
    print(f"  Topics:   {int(best['n_topics'])}")
    print(f"  C_v:      {best['coherence']:.4f}")
    print(f"  IRBO:     {best['irbo']:.4f}")
    print(f"  TQ:       {best['topic_quality']:.4f}")

# Pivot table: TQ by max_df x min_docs (averaged across subjects)
print(f"\n{'='*80}")
print(f"TOPIC QUALITY HEATMAP (averaged across subjects)")
print(f"{'='*80}")
pivot = tuning_df.pivot_table(
    index="min_docs", columns="max_df",
    values="topic_quality", aggfunc="mean"
)
print(pivot.round(4))

Saved: ../../../../results/topicGpt/tunning/cs/tuning_results.csv
Saved: ../../../../results/topicGpt/tunning/math/tuning_results.csv
Saved: ../../../../results/topicGpt/tunning/physics/tuning_results.csv

Combined results saved: ../../../../results/topicGpt/tunning/tuning_results_all.csv

================================================================================
BEST CONFIGURATION PER SUBJECT
================================================================================

CS:
  Model:    sentence_transformers_all_MiniLM_L6_v2
  max_df:   0.8
  min_docs: 200
  Topics:   138
  C_v:      0.7095
  IRBO:     0.9893
  TQ:       0.8264

MATH:
  Model:    sentence_transformers_all_MiniLM_L6_v2
  max_df:   0.9
  min_docs: 250
  Topics:   90
  C_v:      0.7280
  IRBO:     0.9809
  TQ:       0.8358

PHYSICS:
  Model:    all_distilroberta_v1
  max_df:   0.7
  min_docs: 200
  Topics:   74
  C_v:      0.7398
  IRBO:     0.9873
  TQ:       0.8458

================================================================================
TOPIC QUALITY HEATMAP (averaged across subjects)
================================================================================
max_df       0.5     0.6     0.7     0.8     0.9     1.0
min_docs
10        0.7649  0.7692  0.7722  0.7718  0.7679  0.7566
25        0.7778  0.7828  0.7850  0.7856  0.7849  0.7676
50        0.7923  0.7965  0.8007  0.8007  0.7983  0.7770
100       0.8040  0.8109  0.8151  0.8167  0.8153  0.7819
150       0.8099  0.8183  0.8219  0.8252  0.8248  0.7836
200       0.8194  0.8265  0.8307  0.8334  0.8329  0.7851
250       0.8182  0.8266  0.8315  0.8321  0.8304  0.7832

## Save Best Tuning Model

For each subject, save the best `(max_df, min_docs)` assignment + config
as a checkpoint and export the final assignment CSV.

In [10]:
for subject in LIST_SUBJECT:
    if subject not in all_base_assignments:
        continue

    subj_df = tuning_df[tuning_df["subject"] == subject]
    if len(subj_df) == 0:
        continue

    best = subj_df.loc[subj_df["topic_quality"].idxmax()]
    best_max_df = best["max_df"]
    best_min_docs = int(best["min_docs"])
    best_model = best["best_model"]

    print(f"\n{'='*60}")
    print(f"SAVING BEST FOR: {subject.upper()}")
    print(f"  model={best_model}, max_df={best_max_df}, min_docs={best_min_docs}")
    print(f"{'='*60}")

    # Re-apply filtering with best params
    base_df = all_base_assignments[subject]
    df_best = filter_and_reindex_topics(base_df, min_docs=best_min_docs)

    # Recompute metrics for verification
    texts = all_data[subject]["text"].fillna("").tolist()
    metrics = compute_coherence_irbo(df_best, texts, max_df=best_max_df)

    print(f"  Verified: C_v={metrics['coherence']:.4f}  "
          f"IRBO={metrics['irbo']:.4f}  TQ={metrics['topic_quality']:.4f}")
    print(f"  Topics: {df_best['topic_id'].nunique()}  Docs: {len(df_best)}")

    # Save best model checkpoint
    save_checkpoint(
        {
            "assignment_df": df_best,
            "metrics": metrics,
            "config": {
                "best_model": best_model,
                "max_df": best_max_df,
                "min_docs": best_min_docs,
            }
        },
        "tuning_best", subject
    )

    # Export assignment CSV
    df_export = df_best.copy()
    df_export["subject"]    = subject
    df_export["best_model"] = best_model
    df_export["max_df"]     = best_max_df
    df_export["min_docs"]   = best_min_docs
    df_export["coherence"]  = metrics["coherence"]
    df_export["irbo"]       = metrics["irbo"]

    out_csv = RESULT_DIR / subject / "topicgpt_assignments.csv"
    df_export.to_csv(out_csv, index=False)
    print(f"  Saved CSV: {out_csv}")
    print(f"    Columns: {list(df_export.columns)}")
    print(f"    Rows: {len(df_export)}")

============================================================
SAVING BEST FOR: CS
  model=sentence_transformers_all_MiniLM_L6_v2, max_df=0.8, min_docs=200
============================================================
  Verified: C_v=0.7095  IRBO=0.9893  TQ=0.8264
  Topics: 138  Docs: 65516
  Checkpoint saved: ../../../../models/topicGpt/cs/tuning_best.pkl
  Saved CSV: ../../../../results/topicGpt/tunning/cs/topicgpt_assignments.csv
    Columns: ['doc_idx', 'topic_id', 'topic_label', 'confidence', 'original_topic_id', 'subject', 'best_model', 'max_df', 'min_docs', 'coherence', 'irbo']
    Rows: 65516

============================================================
SAVING BEST FOR: MATH
  model=sentence_transformers_all_MiniLM_L6_v2, max_df=0.9, min_docs=250
============================================================
  Verified: C_v=0.7280  IRBO=0.9809  TQ=0.8358
  Topics: 90  Docs: 39176
  Checkpoint saved: ../../../../models/topicGpt/math/tuning_best.pkl
  Saved CSV: ../../../../results/topicGpt/tunning/math/topicgpt_assignments.csv
    Columns: ['doc_idx', 'topic_id', 'topic_label', 'confidence', 'original_topic_id', 'subject', 'best_model', 'max_df', 'min_docs', 'coherence', 'irbo']
    Rows: 39176

============================================================
SAVING BEST FOR: PHYSICS
  model=all_distilroberta_v1, max_df=0.7, min_docs=200
============================================================
  Verified: C_v=0.7398  IRBO=0.9873  TQ=0.8458
  Topics: 74  Docs: 28507
  Checkpoint saved: ../../../../models/topicGpt/physics/tuning_best.pkl
  Saved CSV: ../../../../results/topicGpt/tunning/physics/topicgpt_assignments.csv
    Columns: ['doc_idx', 'topic_id', 'topic_label', 'confidence', 'original_topic_id', 'subject', 'best_model', 'max_df', 'min_docs', 'coherence', 'irbo']
    Rows: 28507

## Final Summary

In [11]:
print(f"\n{'='*80}")
print(f"{'SUBJECT':<12} | {'MODEL':<45} | {'max_df':>6} | {'min_docs':>8} | {'TOPICS':>6} | {'TQ':>6}")
print(f"{'-'*80}")

for subject in LIST_SUBJECT:
    subj_df = tuning_df[tuning_df["subject"] == subject]
    if len(subj_df) == 0:
        continue
    best = subj_df.loc[subj_df["topic_quality"].idxmax()]
    print(f"{subject:<12} | {best['best_model']:<45} | {best['max_df']:>6.1f} | {int(best['min_docs']):>8} | {int(best['n_topics']):>6} | {best['topic_quality']:>6.4f}")

print(f"\nDone! All results saved to {RESULT_DIR.resolve()}")
print(f"Best model checkpoints saved to {CHECKPOINT_DIR.resolve()}/{{subject}}/tuning_best.pkl")

================================================================================
SUBJECT      | MODEL                                         | max_df | min_docs | TOPICS |     TQ
--------------------------------------------------------------------------------
cs           | sentence_transformers_all_MiniLM_L6_v2        |    0.8 |      200 |    138 | 0.8264
math         | sentence_transformers_all_MiniLM_L6_v2        |    0.9 |      250 |     90 | 0.8358
physics      | all_distilroberta_v1                          |    0.7 |      200 |     74 | 0.8458

Done! All results saved to /home/nedo/Kuliah/TA/Program/results/topicGpt/tunning
Best model checkpoints saved to /home/nedo/Kuliah/TA/Program/models/topicGpt/{subject}/tuning_best.pkl